### ISSUE TITLE
40kb db file but count give me 1 table with 0 records

### ISSUE THREAD

**Issue by wanghaisheng** [almarklein/itemdb#7]
```
db = itemdb.ItemDB("transgamers")
print( db.get_table_names())
print(db.count_all("scrape"))
```
I have 4 tables and insert bunch of records and no warnning at all 
![图片](https://user-images.githubusercontent.com/2363295/133447369-a592ed3b-a8db-48a8-a7a6-2456dd279aa1.png)

**Comment by almarklein** [comment]
A database has a certain base size, just to define the structure of the database, builtin tables, indices etc. So this by itself is not surprising.

If you inserted records and these fail to load later, then this is a problem.
