### ISSUE TITLE
SQLite Compatability Issues

### ISSUE THREAD

**Issue by moll-dev** [almarklein/itemdb#9]
Hey there @almarklein 👋🏼 
When testing out timetagger on my workstation, which has an old version of SQLite3 (3.7.17 2013-05-20 00:56:22), it's failing to ensure the user table is created due to that version not supporting the WITHOUT ROWID command found in the "get_unsafe_webtoken" method call.

Just filing this issue to either get a fix in software or a list of minimum versions required for itemdb. The fix was just to update to a newer version of SQLite3.

Thanks!

**Comment by almarklein** [comment]
Hi Thomas, thanks for reporting this!

The `WITHOUT ROWID` is used to omit a column in the table when we don't need the id, which is done here: 
https://github.com/almarklein/itemdb/blob/854a61f01b538ec4b03f9f499c14a7d21193f29f/itemdb.py#L240-L251

The sqlite docs [says](https://www.sqlite.org/withoutrowid.html) that this feature requires SQLite version 3.8.2 (2013-12-06)

**Comment by almarklein** [comment]
Since this requirement is for a version 8 years ago, I don't think a fix should be required.

**Comment by moll-dev** [comment]
No worries! Hopefully if someone encounters the same issue, they can find this issue and just update sqlite3!
